[package]
name = "retry-future"
version = "0.1.0"
authors = ["Adam Chalmers <achalmers@cloudflare.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
reqwest = "0.10"
pin-project = "0.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }

[[example]]
name = "full"